# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0674bb2eac5701f1e0fa3626d3b5517b1c4c883c59634d0b8ba041599870d761064375ba300a25c05ad1cc4182e6e9ed3c69f36a96851230d92510c33631c71a

test:
  secret_key_base: 226a52ab26d8664d230454e0d979f69a513ee565e766d8cb80eba1cc62bc37a02b4f1a691b04d3d7098489d4a81e0b5d22dc49b9920bd9a0564fd7478832afa9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
